name: Go Test

on:
  push:
    branches: ["main", "chore/upgrade-linter"]
  pull_request:
    branches: ["main"]

jobs:
  ci:
    name: 'CI'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0
      - uses: 'moonrepo/setup-toolchain@v0'
      - run: 'moon ci :tests'
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Set up Go
  #       uses: actions/setup-go@v3
  #       with:
  #         go-version: 1.20.7

  #     # - name: Linter
  #     #   run: moon lint

  #     - name: Test
  #       run: moon :tests
